### ISSUE TITLE
data.reduce is not a function

### ISSUE THREAD

**Issue by inbeacon** [KeitaMoromizato/mysql-to-bigquery#4]
Hi,
I get the following error during import:

```
/Users/rvw/proj/Playgrounds_Testing_Languages/nodejs/bigquery/node_modules/mysql/lib/protocol/Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: data.reduce is not a function
    at MySQLtoBigQuery._toTSV (/Users/rvw/proj/Playgrounds_Testing_Languages/nodejs/bigquery/node_modules/mysql-to-bigquery/lib/RDBtoBigQuery.js:135:41)
    at /Users/rvw/proj/Playgrounds_Testing_Languages/nodejs/bigquery/node_modules/mysql-to-bigquery/lib/RDBtoBigQuery.js:126:34
    at wrappedMapper (/Users/rvw/proj/Playgrounds_Testing_Languages/nodejs/bigquery/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/Users/rvw/proj/Playgrounds_Testing_Languages/nodejs/bigquery/node_modules/map-stream/index.js:96:21)
    at Readable.ondata (/Users/rvw/proj/Playgrounds_Testing_Languages/nodejs/bigquery/node_modules/mysql/node_modules/readable-stream/lib/_stream_readable.js:572:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at readableAddChunk (/Users/rvw/proj/Playgrounds_Testing_Languages/nodejs/bigquery/node_modules/mysql/node_modules/readable-stream/lib/_stream_readable.js:195:16)
    at Readable.push (/Users/rvw/proj/Playgrounds_Testing_Languages/nodejs/bigquery/node_modules/mysql/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at Query.<anonymous> (/Users/rvw/proj/Playgrounds_Testing_Languages/nodejs/bigquery/node_modules/mysql/lib/protocol/sequences/Query.js:199:17)
```

**Comment by intotecho** [comment]
I get the same problem. The library is expecting data to be an array. Array.prototype.reduce()
It appears to be fixed in the latest code on github, fix: bug fix `data.reduce`
but the version with the fix v1.0.14 is not published to npm (still on 1.0.13)
