### ISSUE TITLE
Cannot find module './lib/RDBtoBigQuery'

### ISSUE THREAD

**Issue by drdeimos** [KeitaMoromizato/mysql-to-bigquery#5]
Hello. I get error after install module from git
```
$ node app.js 
module.js:471
    throw err;
    ^

Error: Cannot find module './lib/RDBtoBigQuery'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/npm/mysql-to-bigquery/node_modules/mysql-to-bigquery/index.js:1:83)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by drdeimos** [comment]
In node module directory missing lib dir :(
